spring:
  #编码过滤器配置
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  messages:
    encoding: UTF-8
  #数据源配置
  datasource:
    username: root
    password: password
#   password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbootdb?useUnicode=true&characterEncoding=utf8
#   url: jdbc:mysql://192.168.99.100:3306/sakila?useUnicode=true&characterEncoding=utf8
  #配置配置文件
  profiles:
    active: dev

## 端口
server:
  port: 8080

## Mybatis 配置
mybatis:
  typeAliasesPackage: com.hand.city.domain.city.entity
  mapperLocations: classpath:mapper/*.xml

## 配置日志
logging:
  file: log/CityManager02.log
  level:
    com:
      hand:
        demo: debug
    org:
      springframework:
        web: info